services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: "always"
    environment:
      POSTGRES_DB: ClasseMortaDB
      POSTGRES_USER: nuova_utente
      POSTGRES_PASSWORD: nuova_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - roar_net

  springboot-app:
    image: classemorta-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - roar_net

volumes:
  postgres_data:

networks:
  roar_net: