version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ClasseMortaDB
      MYSQL_USER: nuova_utente
      MYSQL_PASSWORD: nuova_password
      MYSQL_ROOT_PASSWORD: nuova_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - roar_net

volumes:
  mysql_data:

networks:
  roar_net:
