version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: "no"
    environment:
      MYSQL_DATABASE: ClasseMortaDB
      MYSQL_USER: nuova_utente
      MYSQL_PASSWORD: nuova_password
      MYSQL_ROOT_PASSWORD: nuova_password
    ports:
      - "3307:3306"  # Porta esposta solo locale
    volumes:
      - mysql_data:/var/lib/mysql  # Persistenza database
    networks:
      - roar_net    # Conferma che entrambi i servizi sono sulla stessa rete

  springboot-app:
    image: classemorta-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    depends_on:   # Assicura che MySQL parta prima
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - roar_net

volumes:
  mysql_data:

networks:
  roar_net:    # Definizione della rete condivisa