spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ClasseMortaDB
    username: nuova_utente
    password: nuova_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect