spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/ClasseMortaDB}
    username: ${SPRING_DATASOURCE_USERNAME:nuova_utente}
    password: ${SPRING_DATASOURCE_PASSWORD:nuova_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect